CREATE TABLE CSE532.DEA_NY (
   	REPORTER_DEA_NO varchar(10) NOT NULL,
   	REPORTER_BUS_ACT varchar(20),
   	REPORTER_NAME varchar(50),
   	REPORTER_ADDL_CO_INFO varchar(50),
   	REPORTER_ADDRESS1 varchar(100),
   	REPORTER_ADDRESS2 varchar(100),
   	REPORTER_CITY varchar(20),
	REPORTER_STATE varchar(20),
	REPORTER_ZIP int,
	REPORTER_COUNTY varchar(20),
	BUYER_DEA_NO varchar(20),
	BUYER_BUS_ACT varchar(50),
	BUYER_NAME varchar(50),
	BUYER_ADDL_CO_INFO varchar(50),
	BUYER_ADDRESS1 varchar(100),
	BUYER_ADDRESS2 varchar(100),
	BUYER_CITY varchar(50),
	BUYER_STATE varchar(50),
	BUYER_ZIP int,
	BUYER_COUNTY varchar(50),
	TRANSACTION_CODE varchar(5),
	DRUG_CODE int,
	NDC_NO int,
	DRUG_NAME varchar(20),
	QUANTITY double,
	UNIT varchar(20),
	ACTION_INDICATOR varchar(10),
	ORDER_FORM_NO varchar(50),
	CORRECTION_NO varchar(50),
	STRENGTH varchar(50),
	TRANSACTION_DATE date,
	CALC_BASE_WT_IN_GM double,
	DOSAGE_UNIT double,
	TRANSACTION_ID int NOT NULL,
	Product_Name varchar(50),
	Ingredient_Name varchar(100),
	Measure varchar(50),
	MME_Conversion_Factor double,
	Combined_Labeler_Name varchar(50),
	Reporter_family varchar(50),
	dos_str double,
	MME double
   )COMPRESS YES ADAPTIVE;