
WITH Q3A AS(SELECT YEAR(TRANSACTION_DATE)||
	CASE 
    WHEN (CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
         THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
    ELSE CAST (MONTH(TRANSACTION_DATE) AS CHAR(2))
END AS YEARDATE,
SUM(DOSAGE_UNIT) AS MONTHLY_COUNT FROM CSE532.DEA_NY GROUP BY (YEAR(TRANSACTION_DATE)||
	CASE 
    WHEN (CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
         THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
    ELSE CAST (MONTH(TRANSACTION_DATE) AS CHAR(2))
END
))
SELECT YEARDATE,MONTHLY_COUNT,AVG(MONTHLY_COUNT) OVER (ORDER BY YEARDATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SMOOTH_COUNT FROM Q3A;
